### ISSUE TITLE
Symfony 4 + Flex possible controller auto-wiring issue

### ISSUE THREAD

**Issue by mhujer** [lexik/LexikDataLayerBundle#3]
I found a probable issue with the autowiring `DataLayerManager` to the Controller. When I add `DataLayerManager` as a constructor parameter to the Controller, there is an exception:

`Cannot autowire service "My\App\HomepageController": argument "$dataLayerManager" of method "__construct()" references class "Lexik\Bundle\DataLayerBundle\Manager\DataLayerManager" but no such service exists. It cannot be auto-registered because it is from a different root namespace.`

It works fine when I try to inject `\Doctrine\ORM\EntityManagerInterface` (so autowiring a class from a different namespace works in general). 

## Possible Workaround
I found this workaround - just add this to `services.yaml`:
```yaml
services:
    Lexik\Bundle\DataLayerBundle\Manager\DataLayerManager: '@lexik_data_layer.manager.data_layer_manager'
    Lexik\Bundle\DataLayerBundle\Collector\CollectorChain: '@lexik_data_layer.collector.collector_chain'
```

Even this works:
```yaml
services:
    Lexik\Bundle\DataLayerBundle\Manager\DataLayerManager:
    Lexik\Bundle\DataLayerBundle\Collector\CollectorChain:
```

----

*Thanks for the Bundle 👍  I really like the idea of mimicking the flash messages behaviour as it works great for tracking conversions after submitting the form + redirect.*

**Comment by slashfan** [comment]
Hi @mhujer thanks for pointing that out ! 

Indeed as specified here [https://symfony.com/doc/current/service_container/autowiring.html#using-aliases-to-enable-autowiring](url) and there [https://symfony.com/doc/current/bundles/best_practices.html#services](url) aliases should be defined in order to make it work with Symfony autowiring. 

Would you mind making a PR to add the alias for the DataLayerManager in the bundle services.xml file ? If you can't I'll make it myself when I can. Thanks !

**Comment by mhujer** [comment]
@slashfan Here is the PR :-) https://github.com/lexik/LexikDataLayerBundle/pull/4
